### PR TITLE
Minor fixes prior to release

### PR DESCRIPTION
**Pull request by wcleveland**
Removed the explicit '+' from the exponent of the scientific notation format (wasn't needed).
Added a scientific notation version of setColumnMeta method to TableHDU

### CODE REVIEW

**Comment by ritchieGitHub** [comment]
give note when you are ready ;-)

**Comment by wcleveland** [comment]
I believe this is the last of the changes. I discovered the metaColumn omission while I was making my Java application conform the the File Format Definition (FFD) at work.

If you are not in a hurry, we could wait until the end of next week (Jul 28) to see if the public archive site manager accepts the sample file I sent him.

**Comment by ritchieGitHub** [comment]
best is that I wait for your tests ;)

**Comment by wcleveland** [comment]
Looks like the site manager will approve the file, so go ahead perform the merge and feel free to release a minor update.

**Comment by attipaci** [comment]
I have incorporated the fixes from this pull request into an unofficial 1.1.5.3-AK2 release on [my fork](https://github.com/attipaci/nom-tam-fits). 

Also, in case you have any further fixes, I'll plan to keep regularly integrating pull requests made to the base repo, at least until the base repo is actively mainained again. (I could no longer bear that so many good fixes were unheeded here...)

**Pull request merged**
