### PR TITLE
Table compression fixes

### PR DESCRIPTION
**Pull request by attipaci**
Several fixes to table compression.

- #557
- #562
- #563
- #567
- #571 
- #575
- #576

### CODE REVIEW

**Comment by attipaci** [comment]
@keastrid,

This PR is ready on my end, now with as much test coverage as can be added without contorting oneself. 

I did confirm interoperability with `fpack`, within the limits that the (ever multiplying) bugs in `fpack` allow. But, I'll wait until your checks before merging it to master, and preparing an release candidate with it...

**Comment by keastrid** [comment]
Thanks! 

It is unfortunate the CFITSIO has had so many issues.

The round trip of data to compressed table and back again via nom.tam seems to work.

I gave it a quick test using the same code as #550, and when trying to funpack it I get:
```
Error processing file: test.fits.fz
  in HDU number 2

FITSIO status = 414: error uncompressing image
Could not find the required ZPCOUNT keyword
Input file is unchanged.
```

Do you see the same?

**Comment by attipaci** [comment]
Hi @keastrid,

I'll look again. Perhaps something I changed during cleaning up because I did not see that error before, at least not with the fpack I have on Fedora...

**Comment by keastrid** [comment]
I was also using the same fpack version, shipped via ubuntu (via wsl).

This is with incremental writing, your recent changes seem to have fixed the issue with the test case. I call `toHDU` then set the column names.

When trying to work with compressing tables with a string column (apparently funpack doesn't allow that), I was trying to disable compression for that column by passing `NO_COMPRESS` as indicated by the javadoc on `CompressedTableHDU#fromBinaryTableHDU`; however, the binary tables only allow the keyword `NOCOMPRESS`, which is not recognized by funpack... 

`NOCOMPRESS` is specified in the FITS spec, so this seems like another fpack bug as well as a documentation typo in nom.tam.

**Comment by keastrid** [comment]
You can pass it along since you already have a line of communication open with them.

Sounds good on the release schedule, thanks!

**Comment by attipaci** [comment]
@keastrid, Thanks for all your help in resolving this 'can-of-worms'. It's really good that you are pushing what this library can do, and I am also happy that the giant mess of how compression was added to this library is slowly getting sorted, at least to the point where it's starting to work more or less as expected, even if the code underneath remains a ridiculously entangled mess...

**Pull request merged**
