### PR TITLE
HashedList and HeaderTest leftovers from prior pull request...

### PR DESCRIPTION
**Pull request by attipaci**
Just a minor fix to HashedList.internalRemove() -- an off-by-one index in the conditional check. HeaderOrderTest has been reinstated to near its original state, and instead a new orderTest() was added to HeaderTest. (I may continue to expand that test a little further still...)

### CODE REVIEW

**Comment by ritchieGitHub** [comment]
Great I will wait with merging till you say so ;)

**Comment by attipaci** [comment]
Hi Ritchie! OK. I think it's ready for the merge...

**Comment by ritchieGitHub** [comment]
Ok, just a note the code is auto formatted so added blanks in comments won't stay there. If you want a special format use the javadoc techniques.

**Comment by ritchieGitHub** [comment]
just a note, I have sende you a private email

**Pull request merged**
