### PR TITLE
Mark supported

### PR DESCRIPTION
**Pull request by mbtaylor**
Address issue #114.

### CODE REVIEW

**Comment by mbtaylor** [comment]
I don't understand why some automated system is adding whitespace-only commits to my code.

**Comment by attipaci** [comment]
Perhaps it's because the mainline repo does not have Codecov.io access yet (and I don't have the privileges to give it). Don't worry too much. But, will add some unit tests for the code changes, making sure all new lines are fully covered? Once that is done, I'll be ready to merge the changes. If you have questions, e.g. about tests and coverage, feel fee to Slack me for help.

**Comment by attipaci** [comment]
I'll merge and fix up the test case if necessary...

**Comment by attipaci** [comment]
All is good! Thanks. Your test case did make it to the merge, it just hid from my view (I'm blind as my wife tells me!)...
And, if you are feeling energetic, and find a way to cover that block of code that wasn't covered, that would be a plus...

**Pull request merged**
