### PR TITLE
Eliminate ColumnDesc.fileSize in favor of .rowLen()

### PR DESCRIPTION
**Pull request by attipaci**
`ColumnDesc.fileSize` which specified the size of column entries in the FITS was not maintained consistently. It is better to use `ColumnDesc.rowLen()` instead to calculate the size of entries on an as-needed basis.

### CODE REVIEW

**Comment by keastrid** [comment]
Thanks for the quick fix!

The output table from the test case appears to work, and trying it with a larger table of actual data also seems to work.

Incremental writing of fits files also seems to be working.

funpack will decompress the example table, but outputs a table with only the first row having a value of 1, the rest are 0. Nom.tam will read it without issue, so I am not sure what is causing this. I have attached them
[here](https://github.com/nom-tam-fits/nom-tam-fits/files/14316215/Test.zip).

**Comment by attipaci** [comment]
@keastrid, Please check out this PR to see if it fixes the compressed table readability issue. (I'll do my own testing in the coming days also).

**Comment by attipaci** [comment]
@keastrid, Cool, I'm happy this worked. (Less happy that such a nasty bug sneaked in, and went unnoticed so long.) I'll check the compressed header again more carefully. Perhaps some other header value is also incorrect, causing funpack to fail (while nom-tam-fits may work with some default, or perhaps because of some non-standard but consistent mishandling...)

I'll also want to see how long this bug existed. I may have introduced it as a regression in 1.18.0, when I have overhauled binary tables, or it may have existed long before then. In either case it would be good to know what releases were affected and put a notice on this bug accordingly...

**Comment by keastrid** [comment]
Sounds good!

**Comment by attipaci** [comment]
Hi @keastrid,

I looked more carefully into the compressed table generated by your example code, and also went trough the compressed table specification in the FITS 4.0 document.

From what I can tell nom-tam stores the table properly. In your example 8 scalar double-precision (1D) columns are compressed into a single tile using `GZIP_2`. They are then stored on the heap as a variable byte array of 34 bytes, starting at offset 0. I'm not sure why funpack is not processing it right, short of the GZIP_2 implementation being incorrect (maybe in nom-tam).

The nom-tam `GZIP_2` uses the standard Java `GZIPOutputStream`, except that it performs the shuffling of bytes before compressing (see `nom.tam.fits.compression.algorithm.gzip2.GZip2Compressor.shuffle()`). Perhaps there is a bug in how the shuffling is performed, which would then result in garbage when done differently, e.g. by funpack... I cannot think of much else wrong here...

**Pull request merged**
